NUMPY-Numerical Python

Advantages of Numpy Arrays:

1.Allows several Mathematical operations

2.Faster opration

for further checking the working and all we can visit numpy_doucmentation on chrome or just copy paste the link give below
https://numpy.org/doc/




we just need to import the library
with any abbrevation we want to use it with

In [1]:
import numpy as np

We will use another library time to get process time to compare the time taken by numpy and list


In [2]:
from time import process_time

List vs Numpy-Time Taken

In [3]:
np_array=np.array([i for i in range(10000)]) #creating the numpy array
#using numpy abbrevation np.array func
start_time=process_time()
np_array**2 #np array orginal raised to the the power 2
# i.e each element of the existing np_array
end_time=process_time()
print(end_time-start_time)

0.00020042199999981136


whereas the same task if done using list would've taken more time

In [4]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i**2 for i in python_list]
end_time=process_time()
print(end_time-start_time)


0.0009605349999999291


it's not much of difference as its was only for 10,000 value but when we'll work with million of data points it'll be quiet significant.

**Numpy Arrays**


In [5]:
np_array=np.array([1,2,3,4])
print(np_array)
type(np_array)

[1 2 3 4]


numpy.ndarray

for a list it would have been a list having values separated by comma

also this "ndarray"  represents n-dimensional array,here it is 1-d array

In [6]:
np_array.shape

(4,)

the ".shape" tells us the number of coloumn and rows in the array

the first value represents the row and 2nd column but here as it's only columns and 1 row so its(4,)

Lets's create 2-d array and check again

In [7]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
b.shape

(2, 4)

Now if we want the decimal values ,i.e conversion from int to deci

we can use the "dtype=float"

In [10]:
c=np.array([(1,2,3,4),(5,6,7,8,)],dtype=float)

print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


**Initial Placeholders in numpy array**

i.e when we sometimes to initally give the array some particular value

1.to create a numpy array of zero

we use the func ".zeros()"and inside the paranthesis we enter the shape of our arrayi.e the no. of rows and columns

it'll create an array with initial values as zero


In [11]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


2.To create array of ones

use ".ones"

In [12]:
y=np.ones((3,3))

print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3.Create an array of particular value


use ".full"

it'll take first value as the dimensions of array and 2nd value as the number with which it has to be initialised

In [13]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


4.Now to create an identity matrix

~all the diagonal elements as 1 and non-diagonal as zero

use".eye"

only mention one value as row/column as it's same for both in this case(square matrix )


In [14]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


5.Create an array with random values

use ".random.random((shape))"

Note:- all the values will be between 0-1

In [15]:
b=np.random.random((3,4))
print(b)

[[0.79680636 0.47100059 0.5286198  0.91854504]
 [0.87834621 0.26658536 0.99076809 0.42422466]
 [0.72981519 0.7377093  0.31870681 0.91882219]]


6.When we want random integer values arrays within a specific range

use".random.randint(range,(shape))


In [16]:
c=np.random.randint(10,100,(3,5))
print(c)

[[92 94 30 39 64]
 [14 69 26 19 92]
 [84 49 34 19 23]]


7.Array with evenly spaced values

use".linspace(range,no of values)

In [17]:
d=np.linspace(10,30,6) #want values btw 10-30 and 6 values from this range
print(d)

[10. 14. 18. 22. 26. 30.]


8.Now if we want values from a specific range to be printed after particular steps  

not just random ones

use".arange(range,length of step)"

In [19]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


9.Convert the list to array

use".asarray(name of the data type/list here)


In [20]:
list2=[10,20,30,40]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40]


numpy.ndarray

**Analysing a numpy array**

In [21]:
c=np.random.randint(10,90,(5,5))
print(c)

[[66 37 53 41 22]
 [71 44 46 65 48]
 [47 70 44 47 84]
 [41 53 58 47 12]
 [77 37 72 44 37]]


In [22]:
#array dimensions using ".shape"
print(c.shape)

(5, 5)


In [23]:
#no. of dimensions
print(c.ndim)

2


In [24]:
#no. of elements in the array
print(c.size)

25


In [25]:
#checking the datatype of values in the array
print(c.dtype)
#int64=64 bit integer values as we know size of int is 4byte

int64


**Mathematical operations on an array**

the "+" will concatinate the two lists if used simply ,i.e we can't add values in case of lists but we can do it in terms of numpy arrays



In [26]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1 + list2)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))

print(a)
print(b)

[[2 4 3]
 [3 4 7]
 [9 2 8]]
[[12 18 18]
 [19 12 13]
 [14 16 14]]


In [30]:
print(a+b) #print(np.add(a,b))

print(a-b) #print(np.subtract(a,b))

print(a*b) #print(np.multiply(a,b))

print(a/b)#print(np.divide(a,b))

[[14 22 21]
 [22 16 20]
 [23 18 22]]
[[-10 -14 -15]
 [-16  -8  -6]
 [ -5 -14  -6]]
[[ 24  72  54]
 [ 57  48  91]
 [126  32 112]]
[[0.16666667 0.22222222 0.16666667]
 [0.15789474 0.33333333 0.53846154]
 [0.64285714 0.125      0.57142857]]


**Array Manipulation**

In [31]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 8 1]
 [2 4 8]]
(2, 3)


In [32]:
#to create the transpose of the given array

#transpose=change rows into columns
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[6 2]
 [8 4]
 [1 8]]
(3, 2)


In [33]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[6 2 9]
 [1 6 5]]
(2, 3)


In [35]:
#we can do the transpose using ".T" as well
trans2=array.T
print(trans2)
print(trans2.shape)

[[6 1]
 [2 6]
 [9 5]]
(3, 2)


In [36]:
#reshaping the array

a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 4 1]
 [9 8 3]]
(2, 3)


In [37]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[2 4]
 [1 9]
 [8 3]]
(3, 2)
